version: '3'

# デバッグ用Taskfileを読み込む（存在する場合）
# debug.yml は .gitignore に含まれているため、個人用設定として自由に編集可能
# サンプルは debug.yml.example を参照
includes:
  debug:
    aliases: [d]
    taskfile: ./.taskfiles/debug.yml
    optional: true

  app:
    taskfile: ./.taskfiles/app.yml
    optional: true

  cheat:
    aliases: [help]
    taskfile: ./.taskfiles/cheat-sheet.yml
    optional: true

vars:
  MODULE_NAME: '{{.MODULE_NAME | default "github.com/eamat/myapp"}}'
  BINARY_NAME: __REPLACE_MODULE_NAME__
  BINARY_PATH: ./bin/{{.BINARY_NAME}}{{exeExt}}

tasks:
  default:
    desc:   list-all
    cmd:    task --list-all
    silent: true

  # dev:
  #   desc: 開発用タスクを順次実行
  #   cmds:


  act:
    desc: ローカルでGitHub Actions CIを実行 (actが必要)
    cmd:  act push -W .github/workflows/ci.yml

  all:
    desc: リント、テスト、ビルドを順次実行
    cmds:
      - task: lint
      - task: test
      - task: build

  build:
    desc: ビルド(ソース変更時) => {{.BINARY_PATH}}
    deps:       [mod-deps]
    sources:    ['**/*.go']
    generates:  ['{{.BINARY_PATH}}']
    cmds:
      - mkdir -p bin
      - go build -o {{.BINARY_PATH}} .

  build:force: [task: clean, task: build]

  build:release:
    desc: リリース品質のバイナリを作る
    vars:
      RELEASE_DIR: bin/release
      RELEASE_PATH: '{{.RELEASE_DIR}}/{{.BINARY_NAME}}{{exeExt}}'
    cmds:
      - go clean
      - task: mod-deps
      - rm -rf {{.RELEASE_PATH}}
      - mkdir -p {{.RELEASE_DIR}}
      - go build  -trimpath -ldflags "-s -w" -o {{.RELEASE_PATH}} .

  clean:
    desc: ビルド成果物を削除 (bin/ 直下のファイルのみ削除)
    cmds:
      - go clean
      - rm -rf ./bin/{{.BINARY_NAME}}{{exeExt}}

  debug:init:
    desc: デバッグ用のタスクの初期化（debug.ymlを作成）
    cmds:
      - cp .taskfiles/debug.yml.sample .taskfiles/debug.yml

  exe:
    desc: ビルドして実行 => {{.BINARY_PATH}} [-- args]
    deps: [build]
    cmd: '{{.BINARY_PATH}} {{.CLI_ARGS}}'

  init:
    desc: go.mod を初期化
    cmds:
      - go mod edit -module {{.MODULE_NAME}}
      - go mod tidy

  lint:
    desc: golangci-lint
    cmd:  golangci-lint run -v

  mod-deps:
    desc: 依存パッケージをインストール
    sources:
      - go.mod
      - go.sum
    cmds:
      - go mod download
      - go mod tidy

  run:
    desc: go run . [-- args]
    cmd:  'go run . {{.CLI_ARGS}}'

  test: go test -v ./...

  test-coverage:
    desc: カバレッジ付きでテストを実行
    cmds:
      - go test -v -coverprofile coverage.out ./...
      - go tool cover -html coverage.out -o coverage.html
