name: Forgejo Actions Demo

on:
  workflow_dispatch:
  push:
    tags:
      - 'demo*'

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Run a one-line script
        run: echo "Hello, Forgejo Actions from M75q-1!"

      - name: Check Debian Version
        run: cat /etc/os-release
