# アクションが動くか確認するためだけのデモ
name: Actions Demo

on:
  push:
    tags:
      - 'demo*'
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Run a one-line script
        run: echo "Hello, world"

      - name: Check OS Version
        run: cat /etc/os-release

      - name: Show GitHub URLs
        run: |
          echo "GITHUB_SERVER_URL=$GITHUB_SERVER_URL"
          echo "GITHUB_API_URL=$GITHUB_API_URL"

      - name: Show GitHub Context
        run: |
          echo "github.server_url=${{ github.server_url }}"
          echo "github.api_url=${{ github.api_url }}"

      - name: Dump github context
        run: |
          echo '${{ toJson(github) }}'
